<!-- //LOCATION: april/Foreclosure/Foreclosure-Process
-->
  <div id="content">
<h1>Forecloser Process</h1> 
<hr/>
<p>The process of foreclosure can be rapid or lengthy and varies from state to state. Other options such as refinancing, a short sale, alternate financing, temporary arrangements with the lender, or even bankruptcy may present homeowners with ways to avoid foreclosure. Websites which can connect individual borrowers and homeowners to lenders are increasingly offered as mechanisms to bypass traditional lenders while meeting payment obligations for mortgage providers. Although there are slight differences between the states, the foreclosure process generally follows a timeline beginning with initial missed payments, moving to a sale being scheduled and finally a redemption period (if available).</p>
<h4 class="subheader">Strict foreclosure/judicial foreclosure</h4>
<hr/>
<p>In the United States, there are two types of foreclosure in most states described by common law. Using a "deed in lieu of foreclosure," or "strict foreclosure", the noteholder claims the title and possession of the property back in full satisfaction of a debt, usually on contract.</p>

<p>In the proceeding simply known as foreclosure (or, perhaps, distinguished as "judicial foreclosure"), the lender must sue the defaulting borrower in state court. Upon final judgment (usually summary judgment) in the lender's favor, the property is subject to auction by the county sheriff or some other officer of the court. Many states require this sort of proceeding in some or all cases of foreclosure to protect any equity the debtor may have in the property, in case the value of the debt being foreclosed on is substantially less than the market value of the real property; this also discourages a strategic foreclosure by a lender who wants to obtain the property. In this foreclosure, the sheriff then issues a deed to the winning bidder at auction. Banks and other institutional lenders may bid in the amount of the owed debt at the sale but there are a number of other factors that may influence the bid, and if no other buyers step forward the lender receives title to the real property in return.</p>

<h4 class="subheader">Nonjudicial foreclosure</h4>
<hr/>
Historically, the vast majority of judicial foreclosures have been unopposed, since most defaulting borrowers have no money with which to hire counsel. Therefore, the U.S. financial services industry has lobbied since the mid-19th century for faster foreclosure procedures that would not clog up state courts with uncontested cases, and would lower the cost of credit (because it must always have the cost of recovering collateral built-in). Lenders have also argued that taking foreclosures out of the courts is actually kinder and less traumatic to defaulting borrowers, as it avoids the in terrorem effects of being sued.

In response, a slight majority of U.S. states have adopted nonjudicial foreclosure procedures in which the mortgagee (or more commonly the mortgagee's servicer's attorney, designated agent, or trustee) gives the debtor a notice of default (NOD) and the mortgagee's intent to sell the real property in a form prescribed by state statute; the NOD in some states must also be recorded against the property. This type of foreclosure is commonly referred to as "statutory" or "nonjudicial" foreclosure, as opposed to "judicial", because the mortgagee does not need to file an actual lawsuit to initiate the foreclosure. A few states impose additional procedural requirements such as having documents stamped by a court clerk; Colorado requires the use of a county "public trustee," a government official, rather than a private trustee specializing in carrying out foreclosures. However, in most states, the only government official involved in a nonjudicial foreclosure is the county recorder, who merely records any pre-sale notices and the trustee's deed upon sale.

In this "power-of-sale" type of foreclosure, if the debtor fails to cure the default, or use other lawful means (such as filing for bankruptcy to temporarily stay the foreclosure) to stop the sale, the mortgagee or its representative conduct a public auction in a manner similar to the sheriff's auction. Notably, the lender itself can bid for the property at the auction, and is the only bidder that can make a "credit bid" (a bid based on the outstanding debt itself) while all other bidders must be able to immediately present the auctioneer with cash or a cash equivalent like a cashier's check. In May 2012, the U.S. Supreme Court, resolved uncertainty surrounding a secured creditor's right to credit bid in a sale under a Chapter 11 bankruptcy plan. In RadLAX Gateway Hotel, LLC v. Amalgamated Bank, 566 U.S. ______ (2012), the Court found it was obligated to interpret the bankruptcy code “clearly and predictably using well established principles of statutory construction” resolving the lingering uncertainties related to credit bidding under a chapter 11 plan and upholding secured creditors’ rights.

The highest bidder at the auction becomes the owner of the real property, free and clear of interest of the former owner, but possibly encumbered by liens superior to the foreclosed mortgage (e.g., a senior mortgage or unpaid property taxes). Further legal action, such as an eviction, may be necessary to obtain possession of the premises if the former occupant fails to voluntarily vacate.
    </div>
<script type="text/javascript">
$(function(){
menuSelect(4);
});
</script>