<!-- //LOCATION: april/Foreclosure/Foreclosure-Facts
-->

  <div id="content">
<h1>Forecloser Facts</h1>
<hr/> 
<p>Foreclosure is a specific legal process in which a lender attempts to recover the balance of a loan from a borrower who has stopped making payments to the lender by forcing the sale of the asset used as the collateral for the loan. Formally, a mortgage lender (mortgagee), or other lien holder, obtains a termination of a mortgage borrower (mortgagor)'s equitable right of redemption, either by court order or by operation of law (after following a specific statutory procedure).</p>

<p>Usually a lender obtains a security interest from a borrower who mortgages or pledges an asset like a house to secure the loan. If the borrower defaults and the lender tries to repossess the property, courts of equity can grant the borrower the equitable right of redemption if the borrower repays the debt. While this equitable right exists, it is a cloud on title and the lender cannot be sure that he (she) can successfully repossess the property. Therefore, through the process of foreclosure, the lender seeks to foreclose (in plain English, immediately terminate) the equitable right of redemption and take both legal and equitable title to the property in fee simple. Other lien holders can also foreclose the owner's right of redemption for other debts, such as for overdue taxes, unpaid contractors' bills or overdue homeowners' association dues or assessments.</p>

<p>The foreclosure process as applied to residential mortgage loans is a bank or other secured creditor selling or repossessing a parcel of real property (immovable property) after the owner has failed to comply with an agreement between the lender and borrower called a "mortgage" or "deed of trust." Commonly, the violation of the mortgage is a default in payment of a promissory note, secured by a lien on the property. When the process is complete, the lender can sell the property and keep the proceeds to pay off its mortgage and any legal costs, and it is typically said that "the lender has foreclosed its mortgage or lien." If the promissory note was made with a recourse clause then if the sale does not bring enough to pay the existing balance of principal and fees the mortgagee can file a claim for a deficiency judgment. In many states in the United States, items included to calculate the amount of a deficiency judgment include: the loan principal, accrued interest and attorney fees less the amount the lender bid at the foreclosure sale.</p>
<h4 class="subheader">Types of foreclosure</h4>
<hr/>
<p>The mortgage holder can usually initiate foreclosure at a time specified in the mortgage documents, typically some period of time after a default condition occurs. Within the United States, Canada and many other countries, several types of foreclosure exist. In the U.S., two of them – namely, by judicial sale and by power of sale – are widely used, but other modes of foreclosure are also possible in a few states.</p>

<p><strong>Foreclosure by judicial sale</strong>, more commonly known as <strong>judicial foreclosure</strong>, which is available in every state (and required in many), involves the sale of the mortgaged property under the supervision of a court, with the proceeds going first to satisfy the mortgage; then other lien holders; and, finally, the mortgagor/borrower if any proceeds are left. Under this system, the lender initiates foreclosure by filing a lawsuit against the borrower. As with all other legal actions, all parties must be notified of the foreclosure, but notification requirements vary significantly from state to state. A judicial decision is announced after the exchange of pleadings at a (usually short) hearing in a state or local court. In some rather rare instances, foreclosures are filed in federal courts.</p>

<p><strong>Foreclosure by power of sale</strong>, also known as <strong>nonjudicial foreclosure</strong>, is authorized by many states if a power of sale clause is included in the mortgage or if a deed of trust with such a clause was used, instead of an actual mortgage. In some states, like California, nearly all so-called mortgages are actually deeds of trust. This process involves the sale of the property by the mortgage holder without court supervision (as elaborated upon below). This process is generally much faster and cheaper than foreclosure by judicial sale. As in judicial sale, the mortgage holder and other lien holders are respectively first and second claimants to the proceeds from the sale.</p>

<p>Other types of foreclosure are considered minor because of their limited availability. Under <strong>strict foreclosure</strong>, which is available in a few states including Connecticut, New Hampshire and Vermont, suit is brought by the mortgagee and if successful, a court orders the defaulted mortgagor to pay the mortgage within a specified period of time. Should the mortgagor fail to do so, the mortgage holder gains the title to the property with no obligation to sell it. This type of foreclosure is generally available only when the value of the property is less than the debt ("under water"). Historically, strict foreclosure was the original method of foreclosure.</p>
    </div>
<script type="text/javascript">
$(function(){
menuSelect(3);
});
</script>